### ISSUE TITLE
Misleading alert when pointing second machine to a shared sync folder

### ISSUE THREAD

**Issue by ilyakam** [utkarsh9891/PackageSync#12]
The `README` currently states:

> + __Second Machine (or after a fresh installation of Sublime Text)__  
On your second machine please wait until all the backup files are available and then simply set the sync folder and PackageSync will automatically pull all available files from that folder. The following message dialog should appear which you just have to confirm.  
> 
> ![OnlineSyncFolder](https://cloud.githubusercontent.com/assets/9902630/8914964/b20c58ae-34bf-11e5-86d3-b478afb161d3.png)

That message dialog is misleading or ambiguous at best. I was afraid to click on it because I did not want to overwrite the changes that were made and synced from the first machine when pointing the second machine to the same shared folder. 

I would suggest changing the wording from:

> Replace it?

…to:

> Switch to it?

**Comment by faelin** [comment]
The reason this modal window appears is because you are trying to store a new backup of your User settings (either an uncompressed backup directory, a compressed backup directory, or a package-list backup file).

The purpose of this new backup replacing the old is to ensure that any preserved packages on the NEWLY ADDED machine (i.e. the second machine) are added to the backup. Because of this, you definitely DO NOT want to "switch to" the existing backup, because this would remove any locally added packages that are not already synced / in the backup.

I believe that perhaps a better change would be to add a limited backup-rotation feature that would allow you to preserve multiple backup copies automatically.
