### ISSUE TITLE
ST4?

### ISSUE THREAD

**Issue by luckman212** [utkarsh9891/PackageSync#13]
Hi @utkarsh9891 👋 
Been using this plugin w/ ST3 for years, it's been excellent!

I switched to ST4 alpha build 4098
Just wondering if you tested this plugin at all - seems to work, but thought I would ask here...

**Comment by utkarsh9891** [comment]
Hi @luckman212 
Great to see that this is still being so actively used. I created this plugin to solve for the initial set of problems I was facing when I started using Sublime. Since I switched to alternative IDEs of late, I have not been using this much. Unfortunately, I haven't really looked into the plugin for a couple of years now.

It would be great if you can take it for a spin and point out if you find any flaws in the same. Would try to fix them over time.

**Comment by luckman212** [comment]
Thanks for replying. Not sure I'm up to that task but I will keep an eye as ST4 emerges from alpha, if there's anything I can do to help I will certainly try.

**Comment by utkarsh9891** [comment]
That would be great. Closing this issue for now.
Thanks for all the love and support!
