### ISSUE TITLE
Deleted all Packages and Settings

### ISSUE THREAD

**Issue by lrecknagel** [utkarsh9891/PackageSync#2]
I installed actual version via Package Control and then all Packages were gone and not saved anywhere!

**Comment by utkarsh9891** [comment]
Hi Lucas,

I'm extremely sorry for this inconvenience. This is the first I am hearing
of this issue and would be glad if you could please revert with the console
logs. This is what you could do to help me and other PackageSync users:
launch sublime and take the sublime logs after 5 seconds --> install any
package that you use and copy the console logs 5 seconds after it is
installed --> relaunch sublime and save the console logs.
It would be great if you could please send me these three logs through to
help me debug your issue.

Also, please send me a list of packages you use so that I can ensure that
none of them are conflicting with PackageSync.

**Comment by lrecknagel** [comment]
Hey Utkarsh,

I´m sorry for that late response. I could not collect this logs because I have instantly refreshed all of my Sublime stuff because I need it to work. But here is my plugin list:
- Babel
- Can I Use
- Color Highlighter
- DocBlockr
- EncodingHelper
- Indent XML
- JavaScript Snippets
- LaTeXing
- LineEndings
- Predawn
- Predawn Monokai
- ReactJS
- SideBarEnhancements
- SublimeCodeIntel
- Sublimemerge Pro
- TrailingSpaces
- W3CValidators

I hope this help you to solve the issue.
Cheers Lucas

**Comment by utkarsh9891** [comment]
Hi Lucas,

I tried several times with the combinations of the packages you mentioned. I myself use almost all of these packages myself but have never faced the said issue.

Can you please try installing PackageSync once again and provide me the Sublime logs?

If you are afraid of your packages getting lost, do the following before installing PackageSync:-
Launch Sublime & go to "Preferences -> Browse Packages". From there, take a backup of the "Users" folder. Once, done, install PackageSync and revert with the Sublime console logs if you face any issues.

If your packages get deleted, just restore the "Users" folder backup & you would be good to go.

**Comment by utkarsh9891** [comment]
Hi Lucas,

Did you try using PackageSync once again?
I still haven't come across anyone who has faced an issue similar to yours. Please revert if you still have this problem. Otherwise, I may have to close this issue on Github.

**Comment by lrecknagel** [comment]
Hi Utkarsh,

I tried it again and it works now, I am sorry for that late response. 
I don´t know why this happend to me at the first time.
Thanks for you great help :+1:

**Comment by utkarsh9891** [comment]
Great. :+1: 
Happy Syncing. :)
